### ISSUE TITLE
trailing whitespace and missing newlines at end of files - pre-commit workaround

### ISSUE THREAD

**Issue by clarsen** [bmadcode/BMAD-METHOD#215]
my pre-commit hooks rewrite most of the files in .bmad and .bmad-core due to trailing whitespace and missing newlines at end of files.

As a workaround, this .pre-commit-hooks.yml:
```yaml
repos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(\.bmad-core|\.bmad)/
      - id: end-of-file-fixer
        exclude: ^(\.bmad-core|\.bmad)/
```
